Iiitirservices:
  - type: web
    name: reia-scraper
    env: python
    plan: free
    buildCommand: |
      apt-get update && \
      apt-get install -y chromium && \
      pip install -r requirements.txt
    startCommand: gunicorn scraper_api:app
    envVars:
      - key: PYTHONUNBUFFERED
        value: "TRUE"
      - key: CHROME_BINARY
        value: "/usr/bin/chromium"
