services:
  - type: web
    name: reia-scraper
    runtime: docker
    repo: https://github.com/prateekbalawat/reia-scraper
    branch: main
    plan: free
    envVars:
      - key: CHROME_BINARY
        value: "/usr/bin/chromium"
