services:
  - type: web
    name: reia-scraper
    env: python
    plan: free
    buildCommand: |
      apt-get update && \
      apt-get install -y wget unzip xvfb libxi6 libgconf-2-4 libnss3 libasound2 libatk1.0-0 libatk-bridge2.0-0 libcups2 libxss1 libxtst6 && \
      wget https://storage.googleapis.com/chrome-for-testing-public/122.0.6261.111/linux64/chrome-linux64.zip && \
      unzip chrome-linux64.zip && \
      mv chrome-linux64 /opt/chrome && \
      ln -s /opt/chrome/chrome /usr/bin/chromium && \
      pip install -r requirements.txt
    startCommand: gunicorn scraper_api:app
    envVars:
      - key: CHROME_BINARY
        value: "/usr/bin/chromium"
